# Generated by Django 4.2.3 on 2023-07-15 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.CharField(db_index=True, max_length=123, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=555)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('order', models.IntegerField(default=0)),
                ('parent_group', models.CharField(max_length=123)),
                ('isIncludedInMenu', models.BooleanField(default=False)),
                ('isGroupModifier', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.CharField(db_index=True, max_length=123, primary_key=True, serialize=False, unique=True)),
                ('weight', models.CharField(max_length=100)),
                ('groupId', models.CharField(max_length=123)),
                ('type', models.CharField(max_length=123)),
                ('parentGroup', models.CharField(max_length=123)),
                ('name', models.CharField(max_length=333)),
            ],
        ),
    ]
